# Generated by Django 4.1.5 on 2023-03-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fname',
            new_name='uname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lname',
        ),
    ]
