# Generated by Django 4.1.5 on 2023-03-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_fname_member_uname_remove_member_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommandos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('move', models.IntegerField(max_length=6)),
                ('apl', models.IntegerField(max_length=6)),
                ('group', models.IntegerField(max_length=6)),
                ('defense', models.IntegerField(max_length=6)),
                ('save', models.IntegerField(max_length=10)),
                ('wounds', models.IntegerField(max_length=50)),
            ],
        ),
    ]
