# Generated by Django 4.1.5 on 2023-03-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_kommandos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kommandos',
            name='apl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kommandos',
            name='defense',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kommandos',
            name='group',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kommandos',
            name='move',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kommandos',
            name='save',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kommandos',
            name='wounds',
            field=models.IntegerField(),
        ),
    ]
