# Generated by Django 4.1.5 on 2023-03-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_kommandos_apl_alter_kommandos_defense_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kommandos',
            new_name='Kommando',
        ),
    ]
