# Generated by Django 4.1.5 on 2023-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_kommandos_kommando'),
    ]

    operations = [
        migrations.CreateModel(
            name='Krieg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('m', models.IntegerField()),
                ('apl', models.IntegerField()),
                ('ga', models.IntegerField()),
                ('df', models.IntegerField()),
                ('sv', models.IntegerField()),
                ('w', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='kommando',
            old_name='name',
            new_name='unit',
        ),
    ]
