# Generated by Django 4.1.5 on 2023-03-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_krieg_rename_name_kommando_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kommando',
            old_name='defense',
            new_name='df',
        ),
        migrations.RenameField(
            model_name='kommando',
            old_name='group',
            new_name='ga',
        ),
        migrations.RenameField(
            model_name='kommando',
            old_name='move',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='kommando',
            old_name='save',
            new_name='sv',
        ),
        migrations.RenameField(
            model_name='kommando',
            old_name='wounds',
            new_name='w',
        ),
    ]
