# Generated by Django 4.1.5 on 2023-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_defense_kommando_df_rename_group_kommando_ga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('m', models.IntegerField()),
                ('apl', models.IntegerField()),
                ('ga', models.IntegerField()),
                ('df', models.IntegerField()),
                ('sv', models.IntegerField()),
                ('w', models.IntegerField()),
            ],
        ),
    ]
