# Generated by Django 4.1.7 on 2023-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_sister'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommando',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
