# Generated by Django 4.1.7 on 2023-04-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_kommando_apl_remove_kommando_df_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommand_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.kommando')),
            ],
        ),
    ]
