# Generated by Django 4.1.7 on 2023-04-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_kommand_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kommand_list',
            name='unit',
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit01',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit01', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit02',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit02', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit03',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit03', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit04',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit04', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit05',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit05', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit06',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit06', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit07',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit07', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit08',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit08', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit09',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit09', to='website.kommando'),
        ),
        migrations.AddField(
            model_name='kommand_list',
            name='unit10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit10', to='website.kommando'),
        ),
    ]
