# Generated by Django 4.1.7 on 2023-04-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_sister_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sister',
            name='apl',
        ),
        migrations.RemoveField(
            model_name='sister',
            name='df',
        ),
        migrations.RemoveField(
            model_name='sister',
            name='ga',
        ),
        migrations.RemoveField(
            model_name='sister',
            name='m',
        ),
        migrations.RemoveField(
            model_name='sister',
            name='sv',
        ),
        migrations.RemoveField(
            model_name='sister',
            name='w',
        ),
        migrations.AddField(
            model_name='sister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
