# Generated by Django 4.1.7 on 2023-04-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_sister_apl_remove_sister_df_remove_sister_ga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krieg',
            name='apl',
        ),
        migrations.RemoveField(
            model_name='krieg',
            name='df',
        ),
        migrations.RemoveField(
            model_name='krieg',
            name='ga',
        ),
        migrations.RemoveField(
            model_name='krieg',
            name='m',
        ),
        migrations.RemoveField(
            model_name='krieg',
            name='sv',
        ),
        migrations.RemoveField(
            model_name='krieg',
            name='w',
        ),
        migrations.AddField(
            model_name='krieg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Krieg_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('unit01', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit01', to='website.krieg')),
                ('unit02', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit02', to='website.krieg')),
                ('unit03', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit03', to='website.krieg')),
                ('unit04', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit04', to='website.krieg')),
                ('unit05', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit05', to='website.krieg')),
                ('unit06', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit06', to='website.krieg')),
                ('unit07', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit07', to='website.krieg')),
                ('unit08', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit08', to='website.krieg')),
                ('unit09', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit09', to='website.krieg')),
                ('unit10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit10', to='website.krieg')),
            ],
        ),
    ]
