# Generated by Django 4.1.7 on 2023-04-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_pm_pm_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pm_list',
            name='unit07',
        ),
        migrations.RemoveField(
            model_name='pm_list',
            name='unit08',
        ),
        migrations.RemoveField(
            model_name='pm_list',
            name='unit09',
        ),
        migrations.RemoveField(
            model_name='pm_list',
            name='unit10',
        ),
    ]
