# Generated by Django 4.1.7 on 2023-04-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_bloodied_cm_dg_dg_list_cm_list_bloodied_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
