# Generated by Django 4.1.7 on 2023-06-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_home_media_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kommand_list',
            table='Kommand_list',
        ),
    ]
