# Generated by Django 4.1.7 on 2023-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_kommand_list_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kommand_list',
            table=None,
        ),
    ]
