from django.contrib import admin
from . models import Member, Kommando, Krieg, Sister, Xeno, Imperium, Chao, Kommand_list,Pm,Pm_list,sister_list,Krieg_list,Eldarg_list,Eldar_g,Tyranid_list,Tyranid_s,Tau_p,Pathfinder_list,Bloodied,Bloodied_list,Dg,Dg_list,Cm,Cm_list,Home_media

admin.site.register(Member)
admin.site.register(Kommando)
admin.site.register(Kommand_list)
admin.site.register(Krieg)
admin.site.register(Krieg_list)
admin.site.register(Sister)
admin.site.register(sister_list)
admin.site.register(Xeno)
admin.site.register(Imperium)
admin.site.register(Chao)
admin.site.register(Pm)
admin.site.register(Pm_list)
admin.site.register(Tyranid_s)
admin.site.register(Tyranid_list)
admin.site.register(Eldar_g)
admin.site.register(Eldarg_list)
admin.site.register(Tau_p)
admin.site.register(Bloodied)
admin.site.register(Bloodied_list)
admin.site.register(Cm)
admin.site.register(Cm_list)
admin.site.register(Dg)
admin.site.register(Dg_list)
admin.site.register(Pathfinder_list)
admin.site.register(Home_media)